### ISSUE TITLE
Getting web assembly type errors while building

### ISSUE THREAD

**Issue by Randy808** [vulpemventures/secp256k1-zkp#52]
Whenever I run the tests after building I get an error that says `Aborted(to do setValue(i64) use WASM_BIGINT). Build with -sASSERTIONS for more info`. When I add `WASM_BIGINT` to `build_wasm`'s `emcc` I get a new error about invalid conversions `Cannot mix BigInt and other types, use explicit conversions`. Is there another step I should take during the build process?

[test-output-with-wasm-bigint.txt](https://github.com/vulpemventures/secp256k1-zkp/files/13310793/test-output-with-wasm-bigint.txt)
[test-output-without-wasm-bigint.txt](https://github.com/vulpemventures/secp256k1-zkp/files/13310794/test-output-without-wasm-bigint.txt)

**Comment by tiero** [comment]
Can you try again with the latest master branch? We have upgraded the toolchain to add musig2

**Comment by Randy808** [comment]
The build issues I was facing are resolved in v3.2.1 🚀
